/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(iq_stream_source.h) */
/* BINDTOOL_HEADER_FILE_HASH(16da234ea576a5e0b56c8fa2460f00ea) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nrf52/iq_stream_source.h>
// pydoc.h is automatically generated in the build directory
#include <iq_stream_source_pydoc.h>

void bind_iq_stream_source(py::module &m) {

  using iq_stream_source = ::gr::nrf52::iq_stream_source;

  py::class_<iq_stream_source, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<iq_stream_source>>(m, "iq_stream_source",
                                                D(iq_stream_source))

      .def(py::init(&iq_stream_source::make), py::arg("freq"),
           py::arg("angle_mode"), D(iq_stream_source, make))

      ;
}
